Repository CopilotKit/CopilotKit, pull requests merged in 2024-11, with the labels that each got.

#861 Create copilotkit-task-manager.md
  community/demos/copilotkit-task-manager.md
Labels: hacktoberfest-accepted

#860 Create VedantCustomContent.md
  community/demos/VedantCustomContent.md
Labels: hacktoberfest-accepted

#852 Language Tranlator added
  community/demos/mayank-mohapatra-language-translator.md
Labels: hacktoberfest-accepted

#854 receipe generator added
  community/demos/mayank-receipe-generator.md
Labels: hacktoberfest-accepted

#830 Added Interactive Flashcards and Quiz Generator
  community/demos/Flashcards_Quiz_ai.md
Labels: hacktoberfest-accepted, ⚔️ Quest

#828 demo:recipe-modifier added (Hacktoberfest Demo)
  community/demos/Recipe-Modifier.md
Labels: hacktoberfest-accepted, ⚔️ Quest

#821 demo: Add Movie recommendation Bot (Hacktoberfest Demo)
  community/demos/movie-bot.md
Labels: hacktoberfest-accepted

#848 custom content added
  community/demos/anshumanrai-Cutom-Content.md
Labels: hacktoberfest-accepted

#859 Demo: Emotion Reads
  community/demos/emotion-reads.md
Labels: hacktoberfest-accepted

#858 Create stocks-assistent.md
  community/demos/stocks-assistent.md
Labels: hacktoberfest-accepted

#857 Demo: ai news aggregator
  community/demos/priyanshu-new-aggregrator.md
Labels: hacktoberfest-accepted

#856 news aggregrator added
  community/demos/mayank_news_generator.md
Labels: hacktoberfest-accepted

#855 Demo: Language translator
  community/demos/priyanshu-language-translator.md
Labels: hacktoberfest-accepted

#853 Demo recipe-modifier
  community/demos/anshuman-recipe-modifier.md
Labels: hacktoberfest-accepted

#822 demo: create cookbook
  community/demos/cookbook.md
Labels: hacktoberfest-accepted, ⚔️ Quest

#819 🎵 demo: AI powered MUSIC lyrics fetcher/finder!
  community/demos/music_lyrics_finder.md
Labels: hacktoberfest-accepted

#729 17 - Interactive Flashcards (Hacktoberfest Demo) #629
  community/demos/quizflip.md
Labels: hacktoberfest-accepted

#886 Feat/preview envs demos 1
  .github/workflows/ci.yml
  .github/workflows/demos_preview.yml
  .github/workflows/quality.yml
  .github/workflows/release.yml
  .gitignore
  examples/coagents-ai-researcher/agent/.dockerignore
  examples/coagents-ai-researcher/agent/Dockerfile
  examples/coagents-ai-researcher/ui/.dockerignore
  examples/coagents-ai-researcher/ui/Dockerfile
  examples/coagents-ai-researcher/ui/next.config.mjs
  examples/coagents-qa-native/agent/.dockerignore
  examples/coagents-qa-native/agent/Dockerfile
  examples/coagents-qa-native/ui/.dockerignore
  examples/coagents-qa-native/ui/Dockerfile
  examples/coagents-qa-native/ui/next.config.mjs
  examples/coagents-qa-text/agent/.dockerignore
  examples/coagents-qa-text/agent/Dockerfile
  examples/coagents-qa-text/ui/.dockerignore
  examples/coagents-qa-text/ui/Dockerfile
  examples/coagents-qa-text/ui/next.config.mjs
  examples/coagents-research-canvas/agent/.dockerignore
  examples/coagents-research-canvas/agent/Dockerfile
  examples/coagents-research-canvas/agent/research_canvas/demo.py
  examples/coagents-research-canvas/ui/.dockerignore
  examples/coagents-research-canvas/ui/Dockerfile
  examples/coagents-research-canvas/ui/next.config.mjs
  examples/coagents-research-canvas/ui/src/app/api/copilotkit/route.ts
  infra/.gitignore
  infra/.npmignore
  infra/README.md
  infra/bin/infra.ts
  infra/cdk.json
  infra/generate-table.js
  infra/jest.config.js
  infra/lib/coagents-demo-stack.ts
  infra/lib/utils.ts
  infra/package-lock.json
  infra/package.json
  infra/pnpm-lock.yaml
  infra/test/infra.test.ts
  infra/tsconfig.json
Labels: preview

#903 chore(ci): preview environments
  .github/workflows/preview-envs-deploy.yml
  .github/workflows/preview-envs-destroy.yml
  infra/bin/infra.ts
  infra/lib/coagents-demo-stack.ts
Labels: preview

#909 chore(previews): use local python sdk
  .dockerignore
  examples/coagents-ai-researcher/agent/Dockerfile
  examples/coagents-qa-native/agent/Dockerfile
  examples/coagents-qa-text/agent/Dockerfile
  examples/coagents-research-canvas/agent/Dockerfile
  infra/bin/infra.ts
  infra/lib/coagents-demo-stack.ts
Labels: preview

#896 fix-4 urls and1 text mistake resolve
  docs/content/docs/reference/components/CopilotTextarea.mdx
  docs/content/docs/reference/components/chat/CopilotChat.mdx
  docs/content/docs/reference/components/chat/CopilotPopup.mdx
  docs/content/docs/reference/components/chat/CopilotSidebar.mdx
  docs/content/docs/reference/components/chat/index.mdx
  docs/package-lock.json
Labels: documentation

#911 fix(langchain-adapter): action descriptions in lc adapter
  CopilotKit/packages/runtime/src/service-adapters/langchain/utils.ts
Labels: preview

#914 Release 1.3.15
  CopilotKit/examples/next-openai/CHANGELOG.md
  CopilotKit/examples/next-openai/package.json
  CopilotKit/examples/next-pages-router/CHANGELOG.md
  CopilotKit/examples/next-pages-router/package.json
  CopilotKit/examples/node-express/CHANGELOG.md
  CopilotKit/examples/node-express/package.json
  CopilotKit/examples/node-http/CHANGELOG.md
  CopilotKit/examples/node-http/package.json
  CopilotKit/packages/react-core/CHANGELOG.md
  CopilotKit/packages/react-core/package.json
  CopilotKit/packages/react-textarea/CHANGELOG.md
  CopilotKit/packages/react-textarea/package.json
  CopilotKit/packages/react-ui/CHANGELOG.md
  CopilotKit/packages/react-ui/package.json
  CopilotKit/packages/runtime-client-gql/CHANGELOG.md
  CopilotKit/packages/runtime-client-gql/package.json
  CopilotKit/packages/runtime/CHANGELOG.md
  CopilotKit/packages/runtime/package.json
  CopilotKit/packages/shared/CHANGELOG.md
  CopilotKit/packages/shared/package.json
  CopilotKit/utilities/eslint-config-custom/CHANGELOG.md
  CopilotKit/utilities/eslint-config-custom/package.json
  CopilotKit/utilities/tailwind-config/CHANGELOG.md
  CopilotKit/utilities/tailwind-config/package.json
  CopilotKit/utilities/tsconfig/CHANGELOG.md
  CopilotKit/utilities/tsconfig/package.json
  docs/content/docs/reference/components/CopilotTextarea.mdx
  docs/content/docs/reference/components/chat/CopilotChat.mdx
  docs/content/docs/reference/components/chat/CopilotPopup.mdx
  docs/content/docs/reference/components/chat/CopilotSidebar.mdx
Labels: preview

#919 chore(docs): add DO NOT MODIFY note for autogenerated reference docs
  CopilotKit/packages/react-textarea/src/components/copilot-textarea/copilot-textarea.tsx
  CopilotKit/packages/react-ui/src/components/chat/Chat.tsx
  CopilotKit/packages/react-ui/src/components/chat/Popup.tsx
  CopilotKit/packages/react-ui/src/components/chat/Sidebar.tsx
  CopilotKit/scripts/docs/lib/reference-doc.ts
  docs/content/docs/reference/classes/CopilotRuntime.mdx
  docs/content/docs/reference/classes/CopilotTask.mdx
  docs/content/docs/reference/classes/llm-adapters/AnthropicAdapter.mdx
  docs/content/docs/reference/classes/llm-adapters/GoogleGenerativeAIAdapter.mdx
  docs/content/docs/reference/classes/llm-adapters/GroqAdapter.mdx
  docs/content/docs/reference/classes/llm-adapters/LangChainAdapter.mdx
  docs/content/docs/reference/classes/llm-adapters/OpenAIAdapter.mdx
  docs/content/docs/reference/classes/llm-adapters/OpenAIAssistantAdapter.mdx
  docs/content/docs/reference/components/CopilotKit.mdx
  docs/content/docs/reference/components/CopilotTextarea.mdx
  docs/content/docs/reference/components/chat/CopilotChat.mdx
  docs/content/docs/reference/components/chat/CopilotPopup.mdx
  docs/content/docs/reference/components/chat/CopilotSidebar.mdx
  docs/content/docs/reference/hooks/useCopilotChat.mdx
  docs/content/docs/reference/hooks/useCopilotChatSuggestions.mdx
  docs/content/docs/reference/hooks/useCopilotReadable.mdx
  docs/next-env.d.ts
Labels: preview

#915 chore(previews): better infra setup for flexibility
  .dockerignore
  .github/workflows/preview-envs-deploy.yml
  .github/workflows/preview-envs-destroy.yml
  examples/Dockerfile.agent
  examples/Dockerfile.ui
  examples/coagents-ai-researcher/agent/.dockerignore
  examples/coagents-ai-researcher/agent/Dockerfile
  examples/coagents-ai-researcher/ui/.dockerignore
  examples/coagents-ai-researcher/ui/Dockerfile
  examples/coagents-ai-researcher/ui/app/api/copilotkit/route.ts
  examples/coagents-qa-native/agent/.dockerignore
  examples/coagents-qa-native/agent/Dockerfile
  examples/coagents-qa-native/ui/.dockerignore
  examples/coagents-qa-native/ui/Dockerfile
  examples/coagents-qa-native/ui/app/api/copilotkit/route.ts
  examples/coagents-qa-text/agent/.dockerignore
  examples/coagents-qa-text/agent/Dockerfile
  examples/coagents-qa-text/ui/.dockerignore
  examples/coagents-qa-text/ui/Dockerfile
  examples/coagents-qa-text/ui/app/api/copilotkit/route.ts
  examples/coagents-qa/ui/app/api/copilotkit/route.ts
  examples/coagents-research-canvas/agent/.dockerignore
  examples/coagents-research-canvas/ui/.dockerignore
  examples/coagents-research-canvas/ui/Dockerfile
  examples/coagents-research-canvas/ui/src/app/api/copilotkit/route.ts
  examples/coagents-research-canvas/ui/src/components/Progress.tsx
  examples/coagents-research-canvas/ui/src/components/ResearchCanvas.tsx
  examples/coagents-research-canvas/ui/src/components/Resources.tsx
  examples/coagents-routing/ui/src/app/api/copilotkit/route.ts
  infra/.gitignore
  infra/bin/infra.ts
  infra/generate-table.js
  infra/lib/coagents-demo-stack.ts
  infra/lib/demo-project-stack.ts
Labels: preview

#922 feat: e2e test setup
  .dockerignore
  .github/workflows/e2e.yml
  .github/workflows/preview-envs-deploy.yml
  examples/Dockerfile.agent
  examples/Dockerfile.ui
  examples/coagents-research-canvas/dockerize.sh
  examples/e2e/.gitignore
  examples/e2e/lib/helpers.ts
  examples/e2e/package.json
  examples/e2e/playwright.config.ts
  examples/e2e/pnpm-lock.yaml
  examples/e2e/tests-examples/demo-todo-app.spec.ts
  examples/e2e/tests-examples/test-copilotkit.ts
  examples/e2e/tests/coagents-canvas-researcher-demo.spec.ts
  infra/bin/infra.ts
  infra/lib/demo-project-stack.ts
Labels: preview

#935 chore: initial Playwright test setup with documentation
  .gitignore
  examples/e2e/README.md
  examples/e2e/package.json
Labels: preview

#933 Versioned & Local Deps for E2E Preview Envs
  .dockerignore
  .github/workflows/preview-envs-deploy.yml
  .github/workflows/preview-envs-destroy.yml
  examples/Dockerfile.agent
  examples/Dockerfile.ui
  infra/bin/infra.ts
  infra/generate-table.js
  infra/lib/demo-project-stack.ts
  infra/lib/utils.ts
Labels: preview

#938 feat(e2e): run against preview envs
  .github/workflows/e2e.yml
  .github/workflows/preview-envs-deploy.yml
  infra/bin/infra.ts
  infra/generate-table.js
  infra/get-e2e-tests-urls.js
  infra/lib/utils.ts
Labels: preview

#945 feat(demos): add coagents-routing to preview envs setup, remove perplexity clone
  .github/workflows/preview-envs-deploy.yml
  examples/coagents-routing/agent/my_agent/demo.py
  examples/coagents-routing/agent/my_agent/model.py
  examples/coagents-routing/ui/.gitignore
  examples/coagents-routing/ui/next.config.mjs
  infra/bin/infra.ts
Labels: preview

#944 docs: updated landing page
  docs/content/docs/(root)/index.mdx
  docs/pnpm-lock.yaml
Labels: preview

#943 connect the flow
  .github/workflows/e2e.yml
  .github/workflows/preview-envs-deploy.yml
  .gitignore
  examples/e2e/.gitignore
  examples/e2e/lib/config-helper.ts
  examples/e2e/package.json
  examples/e2e/playwright.config.ts
  examples/e2e/pnpm-lock.yaml
  examples/e2e/reporters/structured-reporter.ts
  examples/e2e/tests/coagents-canvas-researcher-demo.spec.ts
  infra/get-e2e-tests-urls.js
  infra/lib/utils.ts
Labels: preview

#936 chore: run tests against all models
  examples/e2e/README.md
  examples/e2e/playwright.config.ts
  examples/e2e/reporters/structured-reporter.ts
  examples/e2e/tests/coagents-canvas-researcher-demo.spec.ts
  examples/e2e/tsconfig.json
Labels: preview

#952 add variant
  examples/e2e/lib/variants.ts
  examples/e2e/reporters/structured-reporter.ts
  examples/e2e/tests/coagents-canvas-researcher-demo.spec.ts
Labels: preview

#955 feat(e2e): add tests for coagents routing demo
  examples/coagents-routing/ui/src/app/page.tsx
  examples/e2e/tests/coagents-routing-demo.spec.ts
Labels: preview

#956 chore(e2e): disable google variant for tests
  examples/e2e/lib/variants.ts
  examples/e2e/tests/coagents-canvas-researcher-demo.spec.ts
  examples/e2e/tests/coagents-routing-demo.spec.ts
Labels: preview

#958 chore: updates reference
  examples/e2e/tests/coagents-qa-native-demo.spec.ts
Labels: preview

#957 enhance report
  .github/workflows/e2e.yml
  .github/workflows/preview-envs-deploy.yml
  examples/e2e/package.json
  examples/e2e/pnpm-lock.yaml
  examples/e2e/reporters/structured-reporter.ts
  infra/generate-table.js
Labels: preview

#929 docs(backend-actions): add tabs for FastAPI run step
  docs/content/docs/(root)/guides/backend-actions/remote-backend-endpoint.mdx
Labels: preview

#962 fix(coagents-travel): CoAgents Starter => CoAgents Travel
  examples/coagents-travel/README.md
Labels: preview

#928 fix(coagents-research-canvas): remove container property for Research Canvas
  examples/coagents-research-canvas/ui/src/components/ResearchCanvas.tsx
Labels: preview

#965 feat(next-openai): add cloud support for preview envs
  .github/workflows/e2e.yml
  CopilotKit/examples/next-openai/src/app/components/ServiceAdapterSelector.tsx
  CopilotKit/examples/next-openai/src/app/page.tsx
  CopilotKit/examples/next-openai/src/app/presentation/page.tsx
  CopilotKit/examples/next-openai/src/app/textarea/page.tsx
  CopilotKit/examples/next-openai/src/app/travel/page.tsx
  CopilotKit/packages/runtime-client-gql/tsup.config.bundled_0x2kmnt4uwn.mjs
  CopilotKit/packages/runtime-client-gql/tsup.config.bundled_qpx2b969p4.mjs
  examples/e2e/.gitignore
  examples/e2e/package.json
  examples/e2e/pnpm-lock.yaml
  examples/e2e/tests/coagents-canvas-researcher-demo.spec.ts
  examples/e2e/tests/next-openai.spec.ts
Labels: preview

#969 fixes test reporter
  .github/workflows/e2e.yml
  examples/e2e/playwright.config.ts
  examples/e2e/reporters/structured-reporter.ts
  examples/e2e/tests/coagents-qa-text-demo.spec.ts
Labels: preview

#950 Add support for Azure OpenAI
  CopilotKit/.changeset/pre.json
  CopilotKit/.changeset/selfish-fireants-join.md
  CopilotKit/examples/next-openai/CHANGELOG.md
  CopilotKit/examples/next-openai/package.json
  CopilotKit/examples/next-openai/src/app/components/ServiceAdapterSelector.tsx
  CopilotKit/examples/next-openai/src/lib/dynamic-service-adapter.ts
  CopilotKit/examples/next-pages-router/CHANGELOG.md
  CopilotKit/examples/next-pages-router/package.json
  CopilotKit/examples/node-express/CHANGELOG.md
  CopilotKit/examples/node-express/package.json
  CopilotKit/examples/node-http/CHANGELOG.md
  CopilotKit/examples/node-http/package.json
  CopilotKit/packages/react-core/CHANGELOG.md
  CopilotKit/packages/react-core/package.json
  CopilotKit/packages/react-textarea/CHANGELOG.md
  CopilotKit/packages/react-textarea/package.json
  CopilotKit/packages/react-ui/CHANGELOG.md
  CopilotKit/packages/react-ui/package.json
  CopilotKit/packages/runtime-client-gql/CHANGELOG.md
  CopilotKit/packages/runtime-client-gql/package.json
  CopilotKit/packages/runtime/CHANGELOG.md
  CopilotKit/packages/runtime/package.json
  CopilotKit/packages/runtime/src/service-adapters/openai/openai-adapter.ts
  CopilotKit/packages/shared/CHANGELOG.md
  CopilotKit/packages/shared/package.json
  CopilotKit/utilities/eslint-config-custom/CHANGELOG.md
  CopilotKit/utilities/eslint-config-custom/package.json
  CopilotKit/utilities/tailwind-config/CHANGELOG.md
  CopilotKit/utilities/tailwind-config/package.json
  CopilotKit/utilities/tsconfig/CHANGELOG.md
  CopilotKit/utilities/tsconfig/package.json
Labels: preview

#924 Improve langsmith support
  CopilotKit/.changeset/fluffy-apricots-move.md
  CopilotKit/.changeset/little-falcons-melt.md
  CopilotKit/.changeset/pre.json
  CopilotKit/examples/next-openai/src/lib/dynamic-service-adapter.ts
  CopilotKit/packages/runtime/src/service-adapters/google/google-genai-adapter.ts
  CopilotKit/packages/runtime/src/service-adapters/langchain/langchain-adapter.ts
  docs/content/docs/(root)/(other)/observability/langsmith.mdx
  docs/content/docs/(root)/meta.json
Labels: preview

#984 docs(agentic-copilots): add explantory docs for agentic copilots (rebranded CoAgents)
  CopilotKit/packages/react-core/src/hooks/use-coagent-state-render.ts
  CopilotKit/packages/react-core/src/hooks/use-coagent.ts
  docs/app/(home)/layout.tsx
  docs/components/react/coagents/coagents-enterprise-cta.tsx
  docs/components/react/tailored-content.tsx
  docs/content/docs/(root)/guides/backend-actions/index.mdx
  docs/content/docs/(root)/guides/backend-actions_old.mdx
  docs/content/docs/(root)/index.mdx
  docs/content/docs/(root)/quickstart.mdx
  docs/content/docs/coagents/advanced/manually-emitting-messages.mdx
  docs/content/docs/coagents/advanced/router-mode-agent-lock.mdx
  docs/content/docs/coagents/advanced/state-streaming.mdx
  docs/content/docs/coagents/advanced/using-google-gemini.mdx
  docs/content/docs/coagents/chat-ui/chat-with-agent.mdx
  docs/content/docs/coagents/chat-ui/hitl/json-hitl.mdx
  docs/content/docs/coagents/chat-ui/hitl/text-hitl.mdx
  docs/content/docs/coagents/chat-ui/render-agent-state.mdx
  docs/content/docs/coagents/concepts/copilotkit-config.mdx
  docs/content/docs/coagents/concepts/human-in-the-loop.mdx
  docs/content/docs/coagents/concepts/message-management.mdx
  docs/content/docs/coagents/concepts/meta.json
  docs/content/docs/coagents/concepts/multi-agent-flows.mdx
  docs/content/docs/coagents/concepts/state.mdx
  docs/content/docs/coagents/concepts/terminology.mdx
  docs/content/docs/coagents/concepts/why-agentic-copilots.mdx
  docs/content/docs/coagents/demos/perplexity-clone.mdx
  docs/content/docs/coagents/getting-started.mdx
  docs/content/docs/coagents/index.mdx
  docs/content/docs/coagents/meta.json
  docs/content/docs/coagents/react-ui/frontend-functions.mdx
  docs/content/docs/reference/hooks/useCoAgent.mdx
  docs/content/docs/reference/hooks/useCoAgentStateRender.mdx
  docs/public/images/coagents/coagents-highlevel-overview.png
  docs/public/images/coagents/coagents-state-diagram.png
  docs/public/images/copilotkit-logo.svg
Labels: preview

#990 Fix/new streaming system
  CopilotKit/packages/runtime/src/agents/langgraph/events.ts
  examples/coagents-ai-researcher/agent/pyproject.toml
  examples/coagents-qa-native/agent/poetry.lock
  examples/coagents-qa-native/agent/pyproject.toml
  examples/coagents-qa-text/agent/poetry.lock
  examples/coagents-qa-text/agent/pyproject.toml
  examples/coagents-qa/agent/pyproject.toml
  examples/coagents-research-canvas/agent/poetry.lock
  examples/coagents-research-canvas/agent/pyproject.toml
  examples/coagents-routing/agent/poetry.lock
  examples/coagents-routing/agent/pyproject.toml
  examples/coagents-shared-state/agent/pyproject.toml
  examples/coagents-starter/agent/pyproject.toml
  examples/coagents-travel/agent/pyproject.toml
  examples/coagents-wait-user-input/agent/pyproject.toml
  sdk-python/copilotkit/langgraph_agent.py
Labels: preview

#991 chore: consider possible js deployment url from main config
  examples/e2e/tests/coagents-canvas-researcher-demo.spec.ts
  examples/e2e/tests/coagents-qa-native-demo.spec.ts
  examples/e2e/tests/coagents-qa-text-demo.spec.ts
  examples/e2e/tests/coagents-routing-demo.spec.ts
Labels: preview

#994 fix: fix emitted state being overridden by llm calls
  CopilotKit/packages/runtime/src/lib/runtime/remote-lg-cloud-action.ts
  sdk-python/copilotkit/langgraph_agent.py
Labels: preview

#995 chore: add danger comment when LG executors are not aligned
  .github/workflows/danger.yml
  dangerfile.js
  package.json
  pnpm-lock.yaml
Labels: preview

#996 chore(e2e): test streaming of manually emitted state
  examples/coagents-research-canvas/ui/src/components/Progress.tsx
  examples/e2e/lib/helpers.ts
  examples/e2e/tests/coagents-canvas-researcher-demo.spec.ts
Labels: preview

#978 support streaming multiple messages and refactor rxjs API
  CopilotKit/packages/runtime/src/agents/langgraph/event-source.ts
  CopilotKit/packages/runtime/src/graphql/resolvers/copilot.resolver.ts
  CopilotKit/packages/runtime/src/service-adapters/anthropic/anthropic-adapter.ts
  CopilotKit/packages/runtime/src/service-adapters/events.ts
  CopilotKit/packages/runtime/src/service-adapters/experimental/ollama/ollama-adapter.ts
  CopilotKit/packages/runtime/src/service-adapters/groq/groq-adapter.ts
  CopilotKit/packages/runtime/src/service-adapters/langchain/utils.ts
  CopilotKit/packages/runtime/src/service-adapters/openai/openai-adapter.ts
  CopilotKit/packages/runtime/src/service-adapters/openai/openai-assistant-adapter.ts
  CopilotKit/packages/runtime/src/service-adapters/unify/unify-adapter.ts
Labels: preview
