Repository CopilotKit/CopilotKit, pull requests merged in 2024-10, with the labels that each got.

#656 fixed the typo here in readme
  README.md
Labels: hacktoberfest-accepted

#674 fix(demo): code snippet generator using copilotkit
  community/demos/snippy.md
Labels: hacktoberfest, hacktoberfest-accepted

#661 Added SECURITY.md File #660
  SECURITY.md
Labels: hacktoberfest-accepted

#679 Updated SECURITY.md
  SECURITY.md
Labels: hacktoberfest-accepted

#658 Updated README.md and fixed typos
  README.md
Labels: hacktoberfest-accepted

#659 feat: created CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: hacktoberfest-accepted

#668 Issue #645 Custom CopilotKit Content solved
  community/demos/mayankmohapatra-Custom-Content.md
Labels: hacktoberfest-accepted

#697 fix: update docs contribution link
  README.md
Labels: hacktoberfest-accepted

#726 Fix: Cards not visible in Dark Mode #713
  docs/components/react/coagents/coagents-features.tsx
  docs/content/docs/coagents/index.mdx
Labels: hacktoberfest, hacktoberfest-accepted

#685 Update TEMPLATE.md
  community/content/TEMPLATE.md
Labels: hacktoberfest-accepted

#800 Priority TO-DO list
  community/demos/priority-todolist.md
Labels: hacktoberfest-accepted

#779 demo: Add Task Manager (Hacktoberfest Demo)
  community/demos/task-manager.md
Labels: hacktoberfest-accepted

#778 minor fixes in README.md
  community/content/README.md
Labels: hacktoberfest-accepted

#766 Create language-translator.md
  community/demos/language-translator.md
Labels: hacktoberfest-accepted

#764 DEMO App: Study Sphere
  community/demos/study-sphere.md
Labels: hacktoberfest-accepted

#761 ⭐ 22 - Study Buddy (Hacktoberfest Demo) #634
  community/demos/study-buddy.md
Labels: hacktoberfest-accepted

#751 Added Recipe Generator
  community/demos/Recipe_Generator.md
Labels: hacktoberfest-accepted

#750 Create Copilotkit-weather-bot.md
  community/demos/Copilotkit-weather-bot.md
Labels: hacktoberfest-accepted

#748 ⭐ 27 - Content Summary Tool (Hacktoberfest Demo) - Summarify
  community/demos/summarify.md
Labels: hacktoberfest-accepted

#747 ⭐ 18 - Movie Suggestion Bot (Hacktoberfest Demo) #630
  community/demos/movie-suggestion-bot.md
Labels: hacktoberfest-accepted

#744 19 - Habit Tracker (Hacktoberfest Demo) #631
  community/demos/habittracker.md
Labels: hacktoberfest-accepted

#803 Create content-summary-tool
  community/demos/content-summary-tool.md
Labels: hacktoberfest-accepted

#716 Added community demo: Cal Buddy
  community/demos/cal-buddy.md
Labels: hacktoberfest-accepted

#799 Create Email-Organizer.md
  community/demos/Email-Organizer.md
Labels: hacktoberfest-accepted

#695 05 - Event Planner (Hacktoberfest Demo) #606
  community/demos/EventPlanner.md
Labels: hacktoberfest-accepted, ⚔️ Quest

#711 fix: #678-demo
  community/demos/snippetsorcerer.md
Labels: hacktoberfest-accepted

#728 Added demo and Content : CopilotMate
  community/demos/copilotmate.md
Labels: ⚔️ Quest

#814 🌐 demo: browser extension featuring copilotkit
  community/demos/copilotkit-browser-extension.md
Labels: hacktoberfest-accepted

#824 demo: Add Event Timer Bot (Hacktoberfest Demo)
  community/demos/EventTimer.md
Labels: ⚔️ Quest

#827 Hacktoberfest contribution for Travel Budget Planner #636 and Customer Support bot #786
  community/demos/SwiftSupport.md
  community/demos/TravelTally.md
Labels: ⚔️ Quest

#832 Create daily-quote-generator.md
  community/demos/daily-quote-generator.md
Labels: ⚔️ Quest

#815 docs: Fix typos on certain pages of CopilotKit Docs Site
  docs/content/docs/(root)/(other)/contributing/code-contributions/index.mdx
  docs/content/docs/(root)/guides/custom-look-and-feel/customize-built-in-ui-components.mdx
  docs/content/docs/(root)/quickstart.mdx
  docs/content/docs/(root)/tutorials/ai-powered-textarea/step-3-copilot-textarea.mdx
  docs/content/docs/(root)/tutorials/ai-powered-textarea/step-4-copilot-readable-state.mdx
  docs/content/docs/(root)/tutorials/ai-todo-app/next-steps.mdx
  docs/content/docs/(root)/tutorials/ai-todo-app/step-2-setup-copilotkit.mdx
  docs/content/docs/coagents/advanced/intermediate-state-streaming.mdx
  docs/content/docs/coagents/chat-ui/hitl/text-hitl.mdx
Labels: hacktoberfest-accepted

#825 fixed: typo in ```CopilotKit/examples/coagents-research-canvas/readme.md```
  examples/coagents-research-canvas/readme.md
Labels: hacktoberfest-accepted

#818 Create Legal Document Reviewer Demo
  community/demos/legal-document-reviewer.md
Labels: hacktoberfest-accepted

#846 feat/#608 daily quote app
  community/demos/daily-quote-app.md
Labels: hacktoberfest-accepted

#842 Steph code snippet gen
  community/demos/code-snippet-generator.md
Labels: hacktoberfest-accepted

#840 completed readme.md
  community/demos/news-aggregator.md
Labels: hacktoberfest-accepted

#829 demo: AI powered GitHub Pull Request Tracker
  community/demos/github-pull-request-tracker.md
Labels: hacktoberfest-accepted

#849 Demo anshuman-language-translator.md
  community/demos/anshuman-language-translator.md
Labels: hacktoberfest-accepted

#839 fix: update link in documentation
  community/content/README.md
Labels: hacktoberfest-accepted

#831 feat: add expense tracker demo
  community/demos/expense-tracker.md
Labels: hacktoberfest-accepted

#817 fix: Updated typos in GitHub templates
  .github/ISSUE_TEMPLATE/issue_template.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: hacktoberfest-accepted
